### ISSUE TITLE
endpoint /oauth/user_info return 302

### ISSUE THREAD

**Issue by muriloazevedo** [docusign/docusign-ruby-client#29]
when I call /oauth/user_info, receive 302, but the content doesn't help
```
Connection #0 to host account-d.docusign.com left intact
ETHON: performed EASY effective_url=https://account-d.docusign.com/oauth/token response_code=200 return_code=ok total_time=1.405751
HTTP response body ~BEGIN~
{"access_token":[filtered],"token_type":"Application","expires_in":28800}
~END~

Found bundle for host account-d.docusign.com: 0x7f7a9ce69790 [can pipeline]
Re-using existing connection! (#0) with host account-d.docusign.com
Connected to account-d.docusign.com (64.207.216.101) port 443 (#0)
�GET /restapi/oauth/ HTTP/1.1
Host: account-d.docusign.com
Accept: */*
User-Agent: Swagger-Codegen/3.0.0/ruby
Content-Type: application/json
Authorization: Application [filtered]
X-DocuSign-SDK: Ruby

HHTTP/1.1 302 Found
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Expires: -1
Location: https://account-d.docusign.com/
Server: Microsoft-IIS/8.5
X-AspNetMvc-Version: 5.2
X-DocuSign-TraceToken: f74e9a5e-8cf0-49a2-9277-8a65c31c6f2c
Content-Security-Policy-Report-Only: script-src  'unsafe-eval' 'self'; report-uri /client-errors/csp/report
Content-Security-Policy: script-src 'unsafe-inline' 'unsafe-eval' 'self';style-src 'unsafe-inline' 'self';img-src data: https://docucdn-a.akamaihd.net 'self' https://*.docusign.com https://*.docusign.net https://www.docusign.com.au https://www.docusign.co.uk https://www.docusign.ca;font-src 'self' https://* data:;connect-src 'self' data:;object-src 'none';media-src 'none';frame-src https://docusign.sjv.io https://*.docusign.com; report-uri /client-errors/csp/enforce
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block; report=/client-errors/xss
X-DocuSign-Node: SE2DFE2
Date: Mon, 02 Dec 2019 21:27:49 GMT
Content-Length: 148
Strict-Transport-Security: max-age=15768000

Connection #0 to host account-d.docusign.com left intact
ETHON: performed EASY effective_url=https://account-d.docusign.com/restapi/oauth/ response_code=302 return_code=ok total_time=0.29105
HTTP response body ~BEGIN~
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://account-d.docusign.com/">here</a>.</h2>
</body></html>

~END~

Completed 500 Internal Server Error in 1876ms (ActiveRecord: 6.1ms)


Found excluded from capture: Not configured to send/capture in environment 'development'
  
DocuSign_eSign::ApiError (Found):
  
lib/authorization/docusign.rb:25:in `account_info'
app/graphql/mutations/dashboard/negotiation/notify_buyer_proposal.rb:16:in `resolve'
app/controllers/graphql_controller.rb:10:in `execute'
```

**Comment by LarryKlugerDS** [comment]
Your log shows that you're calling `GET /restapi/oauth/` But you should be calling `/oauth/userinfo`
See the [docs.](https://developers.docusign.com/esign-rest-api/guides/authentication/user-info-endpoints)

You can also see the ruby examples:

* https://github.com/docusign/eg-01-ruby-jwt
* https://github.com/docusign/eg-03-ruby-auth-code-grant

In the future, this type of question is best asked on StackOverflow with tag `docusignapi`
